In [1]:
import os
import pandas as pd
import sys
sys.path.append('/sources')
import matplotlib.pyplot as plt

from preproc import *
from dataset import load_relevant_data_subset

ROOT_PATH = '/sources/dataset/'
df = pd.read_csv(os.path.join(ROOT_PATH, 'train.csv'))

paths = df.path.values
p_ids = df.participant_id.values
s_ids = df.sequence_id.values
labels = df.sign.values

In [9]:
data_idx = 0
pq_file = f'/sources/dataset/{paths[data_idx]}'

lhand_off = np.array([i for i in range(21)])
rhand_off = np.array([i + 21 for i in range(21)])
lip_off = np.array([i + 42 for i in range(40)])
lip = [
            61, 185, 40, 39, 37, 0, 267, 269, 270, 409,
            291, 146, 91, 181, 84, 17, 314, 405, 321, 375,
            78, 191, 80, 81, 82, 13, 312, 311, 310, 415,
            95, 88, 178, 87, 14, 317, 402, 318, 324, 308,
]
lhand = [i for i in range(468, 489)]
rhand = [i for i in range(522, 543)]
POSE = lhand + rhand + lip

In [10]:
xyz = load_relevant_data_subset(pq_file)
xyz = torch.from_numpy(xyz)
print(xyz.shape)

torch.Size([23, 543, 3])


In [13]:
feat = preprocess_xyzd_hdist_v2(xyz, max_len=384)
print(feat.shape)
print(feat)

torch.Size([23, 912])
tensor([[0.0000, 0.0000, 0.0000,  ..., 1.0658, 0.7273, 0.3532],
        [0.0000, 0.0000, 0.0000,  ..., 1.1441, 0.8111, 0.3925],
        [0.0000, 0.0000, 0.0000,  ..., 1.1986, 0.8110, 0.3882],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.8072, 0.4242, 0.1876]])


In [15]:
xyz_feat = feat[:, :82*3]
xyzd_feat = feat[:, 82*3:82*3*2]
ld_feat = feat[:, 82*3*2:82*3*2+210]
rd_feat = feat[:, 82*3*2+210:82*3*2+420]


In [24]:
xyz_feat[0]

tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -2.2117,
         0.8693,  0.1282, -1.5961,  0.6279,  0.2188, -1.3745,  0.4037,  0.2426,
        -1.1537,  0.2383,  0.2146, -0.9090,  0.0871,  0.1794, -1.8742,  0.2549,
         0.3442, -1.6122,  0.0639,  0.2965, -1.2250,  0.0058,  0.2203, -0.8943,
        -0.0120,  0.1642, -2.1082,  0.2579,  0.2336, -1.7913,  0.0167,  0.1583,
        -1.3339, -0.0284,  0.0580, -0.95

In [19]:
xyzd_feat[0]

tensor([ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00, -7.4860e-02,  1.2636e-01,
         1.3858e-06, -9.6769e-02,  1.0989e-01,  2.6

In [20]:
ld_feat[0]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
rd_feat[0]

tensor([0.6612, 0.9579, 0.3152, 1.2319, 0.5895, 0.2759, 1.5195, 0.8744, 0.5630,
        0.2877, 0.7009, 0.4652, 0.5213, 0.7207, 0.9797, 1.0039, 0.5642, 0.4147,
        0.4906, 0.7037, 0.3242, 1.3111, 0.7244, 0.4251, 0.2431, 0.3263, 0.6954,
        0.3916, 1.5849, 0.9497, 0.6351, 0.3604, 0.1001, 1.0155, 0.7219, 0.3311,
        0.6200, 0.6318, 0.7480, 0.9547, 1.2114, 0.2341, 0.5326, 0.9185, 1.2435,
        0.9505, 0.6416, 0.5687, 0.6750, 0.8852, 0.2522, 0.1852, 0.5665, 0.8974,
        0.3982, 1.2555, 0.7067, 0.4340, 0.3218, 0.4403, 0.6101, 0.2933, 0.1142,
        0.4399, 0.8256, 0.4597, 1.5212, 0.8893, 0.5743, 0.3016, 0.0903, 0.9500,
        0.6582, 0.2687, 0.0658, 1.1783, 0.8351, 0.3796, 0.6029, 0.8329, 0.9872,
        1.2016, 1.4588, 0.4811, 0.7740, 1.1631, 1.4897, 0.2475, 0.6231, 1.0671,
        1.4246, 0.8446, 0.7404, 0.7644, 0.9152, 1.1393, 0.2753, 0.4357, 0.8231,
        1.1542, 0.2255, 0.2571, 0.7168, 1.0915, 0.3914, 1.0905, 0.6330, 0.4472,
        0.4717, 0.6558, 0.4083, 0.0866, 